project/project/urls.py
import settings
from django.conf.urls import url
from django.contrib import admin
from project_app import views
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', views.index),
    url(r'^$', views.index),
    url(r'^login/', views.user_login),
    url(r'^register/',views.register),
    url(r'^add_property/', views.add_property),
    url(r'^mypoints/', views.mypoints),
    url(r'^my_properties/', views.my_properties),
    url(r'^properties/(\d{1,4})/$', views.property),
    url(r'^delete_property/(\d{1,4})/$', views.delete_property),
    url(r'^edit_property/(\d{1,4})/$', views.edit_property),
    url(r'^image_delete/(\d{1,4})/$', views.image_delete),
    url(r'^my_notifiers/', views.my_notifiers),
    url(r'^setting/', views.setting),
    url(r'^search/', views.search),
    url(r'^luxury/', views.luxury),
    url(r'^newprojects/', views.newprojects),
    url(r'^viewSingleProject/(\d{1,4})/$', views.viewSingleProject),
    url(r'^luxury_details/(\d{1,4})/$', views.luxury_details),
    url(r'^logout/', views.user_logout),
    url(r'^getcity/', views.getcity),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    url(r'^send_message/', views.sendMessage),
    url(r'^my_notice/', views.viewNotice),
    url(r'^delete_msg/(\d{1,4})/$', views.deleteMessage),
    url(r'^accounts/', include('allauth.urls')),


]

project/project_app/models.py
# encoding: utf-8
from __future__ import unicode_literals
from django.contrib.auth.admin import User
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

# Create your models here.
class Users (models.Model):
	#name=models.CharField(max_length=255)
	#email=models.EmailField()
	#password=models.IntegerField(max_length=32)
	user = models.OneToOneField(User)
	points=models.IntegerField(null=True)
	age=models.IntegerField(null=True)
	token=models.CharField(max_length=255,null=True)
	phone=models.IntegerField(unique=True)
	picture = models.ImageField(upload_to='profile_images', blank=True)
    # Override the __unicode__() method to return out something meaningful!
	def __unicode__(self):
		return unicode(self.user)


	
class Categories (models.Model):
	category_name=models.CharField(max_length=255)
	def __unicode__(self):
		return self.category_name

class Country (models.Model):
	country_name=models.CharField(max_length=255)
	def __unicode__(self):
		return self.country_name

class City (models.Model):
	city_name=models.CharField(max_length=255)
	coun_id=models.ForeignKey(Country)
	def __unicode__(self):
		return self.city_name

class Section (models.Model):
	sec_name=models.CharField(max_length=255)
	def __unicode__(self):
		return self.sec_name

class Property (models.Model):
	prop_name=models.CharField(max_length=255)
	uid=models.ForeignKey(User);
	cat_id=models.ForeignKey(Categories);
	country_id=models.ForeignKey(Country ,default=1);
	city_id=models.ForeignKey(City);
	sec_id=models.ForeignKey(Section);
	address=models.CharField(max_length=255)
	youtube=models.URLField(max_length=255)
	phone=models.IntegerField()
	owner=models.CharField(max_length=255)
	area=models.FloatField()
	price=models.FloatField()
	preview=models.TextField()
	details=models.TextField()
	longtiude=models.TextField()
	Latitude=models.TextField()
	def __unicode__(self):
		return self.uid

class PropertyImage (models.Model):
	pro_id=models.ForeignKey(Property, related_name = "img_pro")
	image_name = models.ImageField(upload_to='property_images', verbose_name='Image',)

class Comments (models.Model):
	coun_id=models.ForeignKey(User, related_name = "user_pro")
	pro_id=models.ForeignKey(Property)
	comment=models.TextField()
	#rec_id=models.ForeignKey(Users ,default=1)

#minaaaaaaaaaaaaaaaaaa#

class NewProjects(models.Model):
	pro_id=models.IntegerField()
	pro_name=models.CharField(max_length=255)
	Description=models.TextField()
	Address=models.TextField()
	Services=models.TextField()
	PaymentMethods=models.TextField()
	DeliveryDate=models.TextField()
	OwnerCompany=models.TextField()
	longtiude=models.FloatField()
	latitude=models.FloatField()
	def __unicode__(self):
		return self.pro_name

class Units(models.Model):
	unit_id=models.IntegerField()
	project_id=models.ForeignKey(NewProjects ,default="1")
	unit_name=models.CharField(max_length=255)
	min_area=models.FloatField()
	max_area=models.FloatField()
	minPrice=models.FloatField()
	maxPrice=models.FloatField()
	def __unicode__(self):
		return self.unit_name

class NewProjectsImage (models.Model):
	proj_id=models.ForeignKey(NewProjects)
	image_name = models.ImageField(upload_to='NewProjects_images', verbose_name='Image',)
	# def __unicode__(self):
	# 	return self.image_name

class Luxury(models.Model):
	lux_id=models.IntegerField()
	lux_name=models.CharField(max_length=255)
	area=models.FloatField()
	price=models.FloatField()
	Description=models.TextField()
	address=models.TextField(default="Maadi")
	longtiude=models.FloatField()
	latitude=models.FloatField()
	def __unicode__(self):
		return self.lux_name

class LuxuryImage (models.Model):
	lux_id=models.ForeignKey(Luxury)
	image_name = models.ImageField(upload_to='Luxury_images', verbose_name='Image',)

#minaaaaaaaaaaaaaaaaaaaa#

project/project_app/views.py
# encoding: utf-8

from django.shortcuts import get_object_or_404
# Create your views here.
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.models import User
from models import *
from forms import *
from django.contrib.auth import *
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.template import *
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.core import serializers
from django.forms.formsets import formset_factory
from django import forms
from django.forms import modelformset_factory
from django.shortcuts import redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render



def index(request):
        property_data = Property.objects.filter().prefetch_related('img_pro')
    
        paginator = Paginator(property_data, 10) # Show 25 contacts per page
        page = request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            contacts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            contacts = paginator.page(paginator.num_pages)

        return render(request, 'home.html', {'contacts': contacts})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                users = Users.objects.all().filter(user=user.id).order_by('id') 
                for x in users :
                    id_u=x.id
                #__setitem__("user_session", request)	
                request.session['user'] = user.username
                request.session['user_id'] = id_u
                request.session['active'] = 1
                return HttpResponseRedirect('/index/')
            else:
                return HttpResponse("Your  account is disabled.")
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'login.html')
#	return render(request,'login.html',{'msg':"success"})	
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print user_form.errors, profile_form.errors
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request,'register.html',{'user_form': user_form, 'profile_form': profile_form, 'registered': registered} )
#	return render(request,'register.html',{'msg':"success"})
@login_required
def add_property(request):
    if request.user.is_authenticated():
    # if "active" in request.session and request.session['active']==1:
        ImageFormSet = modelformset_factory(PropertyImage,form=ImageForm, extra=3)
        if request.method == 'POST':
            obj = User.objects.filter(id=request.user.id)[0]
            objcategory = Categories.objects.filter(id=request.POST['category'])[0]
            objCity = City.objects.filter(id=request.POST['city'])[0]
            objsec = Section.objects.filter(id=request.POST['section'])[0]
            property_form = AddPropertyForm(request.POST)
            #images
            formset = ImageFormSet(request.POST, request.FILES,queryset=PropertyImage.objects.none())

            if property_form.is_valid() :
                request.POST['category']=objcategory
                request.POST['city']=objCity
                request.POST['section']=objsec
                savedata = property_form.save(commit=False)
                savedata.uid = obj
                savedata.cat_id = objcategory
                savedata.city_id = objCity
                savedata.sec_id = objsec
                #savedata.price =  request.POST['price']
                ret=savedata.save()

                c = Property.objects.latest('id')
                #check vlue not null
                for form in formset.cleaned_data:
                        image = form['image_name']
                        photo = PropertyImage(pro_id=c, image_name=image)
                        photo.save()                
                msg ="done "                        
                return render(request,'result_remove.html',{'msg':msg })
            else:
                print property_form.errors
        else:    
            property_form = AddPropertyForm()
            formset = ImageFormSet(queryset=PropertyImage.objects.none())
            #UploadfileFormSet = UploadfileFormSet()
        return render(request,'add_property.html',{'property_form': property_form,'formsetFile': formset})   
    else:
        return HttpResponse("please login required.")

    msg ="removed success "
    return render(request,'result_remove.html',{'msg':msg })
@login_required
def delete_property(request,property_id):
    if request.user.is_authenticated():
        # user = get_object_or_404(Property, user_id=request.user.id)
        u = Property.objects.get(pk=property_id).delete();
        msg ="removed success \n "
        return render(request,'result_remove_image.html',{'msg':msg })
    else:
        return HttpResponse("please login required.")
@login_required
def sendMessage(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            u_id = User.objects.filter(id=request.user.id)[0]
            pro_id = Property.objects.filter(pk=request.POST['pro_id'])[0]
            msg =  request.POST['comment']
            msg_form = msgFormView(request.POST)
            if msg_form.is_valid() :
                savedata = msg_form.save(commit=False)
                savedata.coun_id = u_id
                savedata.pro_id = pro_id
                savedata.comment = msg
                ret=savedata.save()
                return render(request,'result_remove.html',{'msg':'Message Saved Successffully' })
        else :
            return HttpResponse('No Post Found <a href="/index/">Back</a>')
    else :
        return HttpResponse('You Are Not Loged In Please Login From <a href="/login/">Here</a>')

@login_required
def viewNotice(request):
    if request.user.is_authenticated():
        obj = User.objects.filter(id=request.user.id)[0]
        property_data = Property.objects.filter(uid=obj)
        comment_data = Comments.objects.filter()
        return render(request,'viewmyNotice.html',{'property_data':property_data , 'comment_data' : comment_data }) 
        #return HttpResponse('aaaaaaaaaf')
    else :
        return HttpResponse('You Are Not Loged In Please Login From <a href="/login/">Here</a>')


@login_required
def deleteMessage(request,comment_id):
    if request.user.is_authenticated():
        u = Comments.objects.get(pk=comment_id).delete();
        msg ="removed success "
        return render(request,'result_remove.html',{'msg':'Message Deleted Successffully' })
    else :
        return HttpResponse('You Are Not Loged In Please Login From <a href="/login/">Here</a>')    




def property(request,property_id):
    
        property_data = Property.objects.get(pk=property_id)
        property_data_image = PropertyImage.objects.filter(pro_id=property_data)
        property_comments = Comments.objects.filter(pro_id=property_data)

        # property_comments = Comments.objects.filter(pro_id=property_data).prefetch_related('user_pro')
        msgForm = msgFormView()
        return render(request,'viewSingleProperity.html',{'property':property_data ,'images':property_data_image ,'form' : msgForm  ,'property_comments':property_comments})
        #subproperty_data = PropertyImage.objects.get(property_data)
        #return render(request,'viewSingleProperity.html',{'property':property_data , 'subproperty' : subproperty_data})    
@login_required
def image_delete(request,img_id):
    c= PropertyImage.objects.get(pk=img_id)
    u = PropertyImage.objects.get(pk=img_id).delete();
    msg ="removed success "
    return render(request,'result_remove.html',{'msg':msg })
@login_required
def edit_property(request,property_id):

    property_form = AddPropertyForm()
    # image_list = Property.images.all()
    pro = Property.objects.get(pk=property_id)
    image_list = PropertyImage.objects.filter(pro_id=pro)
    if request.method == 'POST':
        obj = User.objects.filter(id=request.user.id)[0]
        objcategory = Categories.objects.filter(id=request.POST['category'])[0]
        objCity = City.objects.filter(id=request.POST['city'])[0]
        objsec = Section.objects.filter(id=request.POST['section'])[0]
        instance = get_object_or_404(Property, id=property_id)
        property_form = AddPropertyForm(request.POST or None, instance=instance)
        if property_form.is_valid() :
            request.POST['category']=objcategory
            request.POST['city']=objCity
            request.POST['section']=objsec
            savedata = property_form.save(commit=False)
            savedata.uid = obj
            savedata.cat_id = objcategory
            savedata.city_id = objCity
            savedata.sec_id = objsec

project/project_app/templates/edit_property.html
{% load staticfiles %}                                                                      
{% include "header.html" %}    
<div class="content_dispaly">
    <h3 class="tit"><span class="glyphicon glyphicon-circle-arrow-right "></span>Edit  property</h3>
        <form id="property_form" class="form col-md-8" method="post" action="/edit_property/{{ property_id }}/"  enctype="multipart/form-data">
            {% csrf_token %}

       {% for field in property_form %}
		    <div class="form-group">
		        {% if field.errors %}
		       	 {{ field.errors }}
		        {% endif %}
		        <label>{{ field.label_tag }}</label>
		        {{ field }}
		        {% if field.help_text %}
		        <p class="help">{{ field.help_text|safe }}</p>
		        {% endif %}
		    </div>
		{% endfor %}
		<p class="text-danger">Click here to remove pic</p>
		{% for c  in image_list %}
	  	 <a href="/image_delete/{{ c.id }}"><img src="/media/{{ c.image_name }}" class="img-rounded img-thumbnail img"  /></a>
	  	 {% endfor %}
			<br/>
		    {{ formsetFile.management_form }}
			    {% for form in formsetFile %}
			        {{ form }}
			    {% endfor %}
          <br/>
          <p class="clearfix"></p>
          <input id="pac-input" class="controls" type="text" placeholder="Search Box">
          <div id="map"></div>

		     <br/>
            <input type="submit" value="Save" class="btn btn-primary"  />
        </form>
		<p class="clearfix"></p>
<script type="text/javascript">
/*$(function(){
	var x={{ request.session.user_id }};
    console.log(x); 
	$('#user_id').val(x);
})
*/	function getCity(){
		var co_id=$('#cat_id').val()
	    $.ajax({
	        url: "/getcity/",
	        data : { id: co_id},
	        success : function(data) {
	            $('#city_id').html(data);
	        }
	    })	
	}	
      // This example adds a search box to a map, using the Google Place Autocomplete
      // feature. People can enter geographical searches. The search box will return a
      // pick list containing a mix of places and predicted search terms.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      function initAutocomplete() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: {{lat}}, lng: {{lang}}},
          zoom: 7,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        });

        // Create the search box and link it to the UI element.
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
         searchBox.setBounds(map.getBounds());
		var lat0 = map.getBounds().getNorthEast().lat();
		var lng0 = map.getBounds().getNorthEast().lng();
		var lat1 = map.getBounds().getSouthWest().lat();
		var lng1 = map.getBounds().getSouthWest().lng();
 		$('#id_longtiude').val(lng0);
 		$('#id_Latitude').val(lat0);
/*		 if(lat0!=null&&lng0!=null){
		 }else{
 			$('#longtiude').val=lng1;
 			$('#Latitude').val=lat1;
		 }
*/          console.log(lat0,lng0);
        });

        var markers = [];
        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

        
          if (places.length == 0) {
            return;
          }

          // Clear out the old markers.
          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];

          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();

          places.forEach(function(place) {
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(25, 25)
            };

            // Create a marker for each place.
            markers.push(new google.maps.Marker({
              map: map,
              icon: icon,
              title: place.name,
              position: place.geometry.location
            }));

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });

          map.fitBounds(bounds);
        });
      }

</script>		





{% include "footer.html" %}    

project/project_app/templates/footer.html
 					</div>
           		 </div>           
 			<footer>
                <p>copyRights iti &copy; 2016</p>
            </footer>
        </div>
    </body>
</html>

project/project_app/templates/header.html
{% load staticfiles %}
{% load socialaccount %}
{% providers_media_js %}

<!DOCTYPE html>
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="windows-1256">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
       	<script type="text/javascript" src="{% static 'js/jquery-1.11.2.js' %}"></script>
       	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>
          <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDC4e5XXwF4gry53DkvzupSn84wKEWrFIk&libraries=places&callback=initAutocomplete"
         async defer></script>  
    </head>
    <body>
        <div class="container-fluid">
            <div class="container">

                <header>
                    <div class="logo pull-left"><img src="{% static 'img/logo.png' %}" width="150px;" /></div>
                    <ul class="list-inline pull-right menu">
                        <li><a href="/"><span class="glyphicon glyphicon-home"></span>Home</a></li>
                    {% if request.user.is_authenticated %}
                        <li>{{ user.username }}!</li>
                        <li><a href="/add_property/">Add property</a></li>
                        <li><a href="/my_notice/">My Notifications</a></li>
                        <li><a href="/my_properties/">My property</a></li>
                        {% else %}
                        <li><a href="/register/">Register </a></li>
                         <li><a href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook Connect</a></li>

                        <li><a href="/login/">Login</a></li>
                        {% endif %}
                        <li><a href="/search/">search</a></li>
                        <li><a href="/newprojects">New Projects</a></li>
                        <li><a href="/luxury">Luxury</a></li>
                        <li><a href="/settings">Setting</a></li>
                        <li><a href="/logout/">Logout</a></li>
                    </ul>
                    <p class="clearfix"></p>
                </header>
                <div class="content">
                    <div class="search"></div>

project/project_app/templates/login.html
{% load staticfiles %}                                                                      
{% include "header.html" %}    
<div class="content_dispaly">
    <h3 class="tit"><span class="glyphicon glyphicon-circle-arrow-right "></span>Login</h3>
        <form id="login_form" class="form col-md-5" method="post" action="/login/">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" class='form-control'/>
            <br />
            Password: <input type="password" name="password" value="" size="50" class='form-control'/>
            <br />

            <input type="submit" value="submit" class="btn btn-primary"  />
        </form>
{% include "footer.html" %}    

project/project_app/templates/luxer_details.html
{% load staticfiles %}                                                                      
{% include "header.html" %}    
<div class="content_dispaly" style="color:#fff">
    <h3 class="tit"><span class="glyphicon glyphicon-circle-arrow-right "></span>{{   projects.lux_name }}</h3>


<div class="row">
	  	 {% for c  in images %}
		  	 	<!--<img src="property_images/{{ c.image_name }}" />-->
		  	 	<div class="col-sm-4">
		  	 		<img class="img-responsive img-thumbnails" src="{{ MEDIA_URL }} /media/{{ c.image_name }}" />	
		  	 	</div>
		  	 	
	  	 {% endfor %}
  	</div>

	  		<div class="row">
	  			<div class="col-sm-4"> luxury Name : </div>
	  			<div class="col-sm-8"> {{ projects.lux_name}}  </div>	
	  		</div>

	  		<div class="row">
	  			<div class="col-sm-4"> area : </div>
	  			<div class="col-sm-8"> {{projects.area}}  </div>	
	  		</div>
	 		
	 		<div class="row">
	  			<div class="col-sm-4"> Address </div>
	  			<div class="col-sm-8"> {{ projects.address}}  </div>	
	  		</div>

	  		<div class="row">
	  			<div class="col-sm-4"> price : </div>
	  			<div class="col-sm-8"> {{ projects.price }}  </div>	
	  		</div>

	  		<div class="row">
	  			<div class="col-sm-4"> Descrition : </div>
	  			<div class="col-sm-8"> {{ projects.Description }}  </div>	
	  		</div>

	  		


  	</div>

  </div>
	 


{% include "footer.html" %}    

project/project_app/templates/my_properties.html
{% load staticfiles %}                                                                      
{% include "header.html" %}    

<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead class="thead-inverse">
	    <tr>
	    	<th>id</th>
	    	<th>title</th>
	    	<th>Property Type</th>
	    	<th>Section</th>
	    	<th>area </th>
	    	<th>price</th>
	    	<th>action</th>
	    </tr>
    </thead>
	    {% for v in property_data %}
			<tr>
				<td>{{ v.id }}</td>
				<td>{{ v.prop_name }}</td>
				<td>{{ v.cat_id }}</td>
				<td>{{ v.sec_id }}</td>
				<td>{{ v.area }}</td>
				<td>{{ v.price }}</td>
				<td><a href="/edit_property/{{ v.id }}">edit</a> | <a href="/delete_property/{{ v.id }}">delete</a></td>
			</tr>
	    {%endfor%}
  </table>
</div>


{% include "footer.html" %}    

project/project_app/templates/newprojects.html
{% load staticfiles %}                                                                      
{% include "header.html" %} 
<div class="content_dispaly" >
<h3 class="tit"><span class="glyphicon glyphicon-circle-arrow-right "></span>NewProjects</h3>






<div class="row">
	<div class="col-sm-12  tit">
		<div class="content-display">
		
			{%for proj in contacts %}
				    <div class="col-md-4 proj">
				        <img src="{% static 'images/d.jpg' %}" class="img-responsive img-rounded" alt=""/>
				        <h3><a href="">{{proj.pro_name}}</a></h3>
				        <p class="details"> 
				        	{{proj.Address}}
				        	<!--{{proj.unit_id.minPrice}}-->
				        </p>
				        <a href="/viewSingleProject/{{proj.id}}" target="_blank" class="btn btn-primary pull-right">Details</a>
				        <p class="clearfix"></p>
				    </div>
				    {% empty %}
					there is no result Matched
			{%endfor%}

		</div>

	</div>


</div>
<div class="row" style="color:#FFF">
    <div class="pagination">
        <span class="step-links">
            {% if contacts.has_previous %}
                <a style="color:#FFF" href="?page={{ contacts.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
            </span>

            {% if contacts.has_next %}
                <a style="color:#FFF" href="?page={{ contacts.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
</div>






</div>

{% include "footer.html" %}  

project/project_app/templates/register.html
{% load staticfiles %}       
{% include "header.html" %}    
<div class="content_dispaly">
    <h3 class="tit"><span class="glyphicon glyphicon-circle-arrow-right "></span>register</h3>
{% if registered %}
        <strong>thank you for registering!</strong>
        <a href="/index/">Return to the homepage.</a><br />
{% else %}
    <form id="user_form" method="post" class="form col-md-5" role="form" action="/register/" enctype="multipart/form-data">      
      <!--{{ user_form.as_p }}-->
        {% csrf_token %}
        {% for field in user_form %}
		    <div class="form-group">
		        {% if field.errors %}
		       	 {{ field.errors }} {{ field.label_tag }}
		        {% endif %}
		        <label>{{ field.label_tag }}</label>
		        {{ field }}
		        {% if field.help_text %}
		        <p class="help">{{ field.help_text|safe }}</p>
		        {% endif %}
		    </div>
		{% endfor %}
		{% for field in profile_form %}
		    <div class="form-group">
		        {% if field.errors %}
		       	 {{ field.errors }} {{ field.label_tag_as_span }}
		        {% endif %}
		        <label>{{ field.label_tag }}</label>
		         {{ field }}
		        {% if field.help_text %}
		        <p class="help">{{ field.help_text|safe }}</p>
		        {% endif %}
		    </div>
		{% endfor %}
    <!--    {{ profile_form.as_div }} -->
        <input type="submit" name="submit" class="btn btn-primary" value="Register" />
    </form>
{% endif %}
</div>
{% include "footer.html" %}    

project/project_app/templates/result_remove.html
{% load staticfiles %}                                                                      
{% include "header.html" %}    

<div class="table-responsive">
  
  <div class="bg-success text-center">{{msg}} <br/><a href="/my_properties/">back to  list </a></div>
</div>


{% include "footer.html" %}    

project/project_app/templates/result_remove_image.html
{% load staticfiles %}                                                                      
{% include "header.html" %}    

<div class="table-responsive">
  
  <div class="bg-success text-center"> {{msg}}  <br/><a href="/my_properties/">back to property {{ pro  }}</a></div>
</div>


{% include "footer.html" %}    